var PostsIniciais = [
  {
    id: 101,
    autorId: "ana",
    autor: "Ana Machado",
    avatar: "assets/images/pedidos-de-ajuda/Ellipse 5.png",
    categoria: "perdidos",
    titulo: "Meu gato desapareceu",
    texto: "O Flocos desapareceu na região do Parque Ibirapuera. Ele é dócil e atende pelo nome.",
    local: "São Paulo, SP",
    imagem: "assets/images/pets-perdidos/snow.jpg",
    urgente: true,
    status: "desaparecido",
    curtidas: 24,
    apoios: 46,
    curtido: false,
    apoiado: false,
    criadoEm: new Date(Date.now() - 7200000).toISOString(),
    comentarios: [
      {
        id: 1,
        autorId: "maria",
        autor: "Maria Santos",
        texto: "Vou compartilhar nos grupos do bairro.",
        data: new Date(Date.now() - 4200000).toISOString(),
      },
      {
        id: 2,
        autorId: "paulo",
        autor: "Paulo Lima",
        texto: "Vi um gato parecido perto da Avenida República do Líbano.",
        data: new Date(Date.now() - 2100000).toISOString(),
      },
    ],
  },
  {
    id: 102,
    autorId: "rafael",
    autor: "Rafael Lima",
    avatar: "assets/images/pedidos-de-ajuda/Ellipse 6.png",
    categoria: "adocao",
    titulo: "Filhote procurando um lar",
    texto: "Este é Luke! Ele tem 3 meses, já tomou a primeira vacina e é muito brincalhão.",
    local: "São Paulo, SP",
    imagem: "assets/images/home/CachorroInicio.png",
    urgente: false,
    status: "disponivel",
    curtidas: 14,
    apoios: 36,
    curtido: false,
    apoiado: false,
    criadoEm: new Date(Date.now() - 14400000).toISOString(),
    comentarios: [],
  },
  {
    id: 103,
    autorId: "ong-patinhas",
    autor: "Projeto Patinhas",
    avatar:
      "assets/images/home/LogoSOSPet.png",
    categoria: "ajuda",
    titulo: "Precisamos de ração!",
    texto: "Nossa ONG está com estoque baixo de ração. Toda ajuda é bem-vinda!",
    local: "São Paulo, SP",
    imagem:
      "assets/images/perfil/racao.jpg",
    urgente: false,
    status: "aberto",
    curtidas: 31,
    apoios: 27,
    curtido: false,
    apoiado: false,
    criadoEm: new Date(Date.now() - 21600000).toISOString(),
    comentarios: [],
  },
  {
    id: 104,
    autorId: "roberta",
    autor: "Roberta Silva",
    avatar: "assets/images/pedidos-de-ajuda/Ellipse 5 (1).png",
    categoria: "ajuda",
    titulo: "Tratamento de Clarêncio",
    texto: "Preciso de apoio para o tratamento do meu passarinho. Toda ajuda é bem-vinda!",
    local: "São Paulo, SP",
    imagem: "assets/images/animais-de-rua/cintya-marisa-3ffJg5D3RLo-unsplash.jpg",
    urgente: false,
    status: "recebendo-ajuda",
    curtidas: 31,
    apoios: 27,
    curtido: false,
    apoiado: false,
    criadoEm: new Date(Date.now() - 10800000).toISOString(),
    comentarios: [],
  },
];
var PedidosIniciais = [
  {
    id: 201,
    autorId: "matheus",
    autor: "Matheus Souza",
    avatar: "assets/images/pedidos-de-ajuda/Ellipse 5.png",
    categoria: "adocao",
    titulo: "Precisamos de um lar temporário",
    descricao:
      "Temos 4 filhotes que foram resgatados e precisam de um lar temporário até serem adotados.",
    local: "São Paulo, SP",
    imagem: "assets/images/pedidos-de-ajuda/lesya-tyutrina-andrey-biyanov-V_8XBgvMyEo-unsplash.jpg",
    urgente: true,
    status: "aberto",
    criadoEm: new Date(Date.now() - 18000000).toISOString(),
    ajudas: [],
  },
  {
    id: 202,
    autorId: "joao",
    autor: "João Victor",
    avatar: "assets/images/pedidos-de-ajuda/Ellipse 6.png",
    categoria: "ajuda",
    titulo: "Precisamos de ração",
    descricao:
      "Nossa ONG está com estoque baixo de ração para cães e gatos. Toda doação é bem-vinda!",
    local: "São Paulo, SP",
    imagem: "assets/images/pedidos-de-ajuda/david-d-angelo-xWKBOhVXBQ4-unsplash.jpg",
    urgente: false,
    status: "recebendo-ajuda",
    criadoEm: new Date(Date.now() - 10800000).toISOString(),
    ajudas: [],
  },
  {
    id: 203,
    autorId: "patricia",
    autor: "Patrícia Mendes",
    avatar: "assets/images/pedidos-de-ajuda/Ellipse 5 (1).png",
    categoria: "perdidos",
    titulo: "Cachorro preso no bueiro",
    descricao:
      "Um cachorro caiu em um bueiro na Vila Mariana e precisa de ajuda para ser resgatado.",
    local: "São Paulo, SP",
    imagem: "assets/images/pedidos-de-ajuda/crt_74023_59_687e4db8312b3.jpeg",
    urgente: true,
    status: "aberto",
    criadoEm: new Date(Date.now() - 18000000).toISOString(),
    ajudas: [],
  },
];
